# ============================================
# EJERCICIO 1: Reporte de Configuración Multi-Ambiente
# ============================================

resource "local_file" "environment_config_report" {
  filename = "${path.module}/reports/environment-config-${var.environment}.json"
  content = jsonencode({
    environment = var.environment
    timestamp   = timestamp()
    config      = local.current_environment_config
    all_environments = {
      for env, config in local.environment_configs :
      env => {
        instance_type    = config.instance_type
        replicas         = "${config.min_replicas}-${config.max_replicas}"
        storage_gb       = config.storage_size
        monthly_cost_usd = config.monthly_cost
        features = {
          monitoring = config.enable_monitoring
          cdn        = config.cdn_enabled
          waf        = config.waf_enabled
          ssl        = config.ssl_required
        }
      }
    }
  })
}

resource "local_file" "cost_estimation" {
  filename = "${path.module}/reports/cost-estimation-${var.environment}.txt"
  content  = <<-EOF
    COST ESTIMATION REPORT
    ======================
    
    Application: ${var.app_name}
    Environment: ${var.environment}
    Generated: ${timestamp()}
    
    Current Environment Costs:
    --------------------------
    Instance Type: ${local.current_environment_config.instance_type}
    Min Replicas: ${local.current_environment_config.min_replicas}
    Max Replicas: ${local.current_environment_config.max_replicas}
    Monthly Cost (min): $${local.current_environment_config.monthly_cost}
    Storage: ${local.current_environment_config.storage_size} GB
    
    All Environments Comparison:
    ----------------------------
    %{for env, config in local.environment_configs~}
    ${upper(env)}:
      - Instance: ${config.instance_type}
      - Replicas: ${config.min_replicas}-${config.max_replicas}
      - Monthly Cost: $${config.monthly_cost}
      - Storage: ${config.storage_size} GB
      - CDN: ${config.cdn_enabled ? "✅" : "❌"}
      - WAF: ${config.waf_enabled ? "✅" : "❌"}
    
    %{endfor~}
    Total Monthly Cost (all environments): $${sum([for env, config in local.environment_configs : config.monthly_cost])}
  EOF
}

# ============================================
# EJERCICIO 2: Reporte de Validación
# ============================================

resource "local_file" "validation_report" {
  filename = "${path.module}/reports/validation-report-${var.environment}.txt"
  content  = <<-EOF
    VALIDATION REPORT
    =================
    
    Environment: ${var.environment}
    Timestamp: ${timestamp()}
    
    Application Configuration:
    --------------------------
    Name: ${var.application_config.name}
    Memory: ${var.application_config.runtime.memory} MB
    CPU: ${var.application_config.runtime.cpu} cores
    Memory/CPU Ratio: ${local.memory_cpu_ratio}

    Validation Results:
    -------------------
    %{for check, result in local.configuration_validation~}
    ${result ? "✅" : "❌"} ${check}: ${result}
    %{endfor~}
    
    Overall Status: ${local.all_validations_passed ? "✅ PASSED" : "❌ FAILED"}
    
    %{if !local.all_validations_passed~}
    ⚠️  WARNING: Please fix the failing validations before proceeding.
    %{endif~}
    
    Features Status:
    ----------------
    ${var.application_config.features.monitoring ? "✅" : "❌"} Monitoring
    ${var.application_config.features.backup ? "✅" : "❌"} Backup
    ${var.application_config.features.logging ? "✅" : "❌"} Logging
  EOF
}

# ============================================
# EJERCICIO 3: Configuraciones de Microservicios
# ============================================

# Crear directorio para configuraciones de servicios
resource "local_file" "services_directory_readme" {
  filename = "${path.module}/services/README.md"
  content  = <<-EOF
    # Microservices Configuration
    
    This directory contains auto-generated configuration files for each microservice.
    
    Generated: ${timestamp()}
    Environment: ${var.environment}
    
    ## Services:
    %{for service_name, config in local.service_configs~}
    - **${service_name}**: ${config.language} on port ${config.health_check.port}
    %{endfor~}
  EOF
}

# Generar archivos de configuración para cada servicio
resource "local_file" "service_configs" {
  for_each = local.service_configs

  filename = "${path.module}/services/${each.key}-config.yaml"
  content  = <<-EOF
    # Configuration for ${each.key} service
    # Auto-generated by Terraform
    
    service:
      name: ${each.value.name}
      language: ${each.value.language}
      environment: ${var.environment}
      
    network:
      internal_url: ${each.value.internal_url}
      port: ${each.value.health_check.port}
      
    resources:
      cpu: ${each.value.resources.cpu}
      memory: ${each.value.resources.memory}
      replicas: ${each.value.replicas}
      
    health_check:
      path: ${each.value.health_check.path}
      port: ${each.value.health_check.port}
      
    environment_variables:
    %{for key, value in each.value.environment_vars~}
      ${key}: "${value}"
    %{endfor~}
    
    dependencies:
    %{for dep in each.value.dependencies~}
      - ${dep}
    %{endfor~}
    
    tags:
    %{for key, value in local.common_tags~}
      ${key}: "${value}"
    %{endfor~}
  EOF
}

# Generar mapa de dependencias
resource "local_file" "dependency_map" {
  filename = "${path.module}/reports/dependency-map-${var.environment}.txt"
  content  = <<-EOF
    MICROSERVICES DEPENDENCY MAP
    ============================
    
    Environment: ${var.environment}
    Generated: ${timestamp()}
    
    Service Dependencies:
    ---------------------
    %{for service_name, config in local.service_configs~}
    
    📦 ${upper(service_name)} (${config.language})
       URL: ${config.internal_url}
       Replicas: ${config.replicas}
       Resources: ${config.resources.cpu} CPU, ${config.resources.memory} Memory
       
       Depends on:
       %{if length(config.dependencies) > 0~}
       %{for dep in config.dependencies~}
       └─ ${dep}
       %{endfor~}
       %{else~}
       └─ (no dependencies)
       %{endif~}
       
       Used by:
       %{if length(local.service_dependents[service_name]) > 0~}
       %{for dependent in local.service_dependents[service_name]~}
       └─ ${dependent}
       %{endfor~}
       %{else~}
       └─ (no dependents)
       %{endif~}
    
    %{endfor~}
    
    Deployment Order (based on dependencies):
    -----------------------------------------
    1. ${join(", ", [for svc, cfg in var.microservices : svc if length(cfg.dependencies) == 0])}
    2. ${join(", ", [for svc, cfg in var.microservices : svc if length(cfg.dependencies) == 1])}
    3. ${join(", ", [for svc, cfg in var.microservices : svc if length(cfg.dependencies) > 1])}
  EOF
}

# Generar archivo de resumen general
resource "local_file" "advanced_exercises_summary" {
  filename = "${path.module}/reports/advanced-exercises-summary-${var.environment}.txt"
  content  = <<-EOF
    ╔════════════════════════════════════════════════════════════════╗
    ║         TERRAFORM ADVANCED EXERCISES - SUMMARY REPORT          ║
    ╚════════════════════════════════════════════════════════════════╝
    
    Student: ${var.student_name}
    Project: ${var.project_name}
    Environment: ${var.environment}
    Generated: ${timestamp()}
    
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    📊 EXERCISE 1: Multi-Environment Configuration System
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    ✅ Implemented environment configurations for: ${join(", ", keys(var.environments))}
    ✅ Auto-sizing storage: ${local.current_environment_config.storage_size} GB
    ✅ Cost estimation: $${local.current_environment_config.monthly_cost}/month
    ✅ Feature flags: CDN=${local.current_environment_config.cdn_enabled}, WAF=${local.current_environment_config.waf_enabled}
    
    Current Environment Details:
    - Instance Type: ${local.current_environment_config.instance_type}
    - Replicas: ${local.current_environment_config.min_replicas}-${local.current_environment_config.max_replicas}
    - Monitoring: ${local.current_environment_config.enable_monitoring ? "Enabled" : "Disabled"}
    - SSL Required: ${local.current_environment_config.ssl_required ? "Yes" : "No"}
    
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    🔍 EXERCISE 2: Advanced Configuration Validator
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    Validation Status: ${local.all_validations_passed ? "✅ ALL CHECKS PASSED" : "❌ SOME CHECKS FAILED"}
    
    Checks Performed:
    %{for check, result in local.configuration_validation~}
    ${result ? "✅" : "❌"} ${replace(check, "_", " ")}
    %{endfor~}
    
    Application Runtime:
    - Memory: ${var.application_config.runtime.memory} MB
    - CPU: ${var.application_config.runtime.cpu} cores
    - Memory/CPU Ratio: ${local.memory_cpu_ratio} (valid range: 256-2048)
    
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    🚀 EXERCISE 3: Dynamic Configuration Generator
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    ✅ Generated configurations for ${length(local.service_configs)} microservices
    ✅ Created dependency map
    ✅ Auto-configured health checks per language
    ✅ Generated environment variables with service URLs
    
    Microservices Summary:
    %{for service_name, config in local.service_configs~}
    • ${service_name}: ${config.language} | ${config.replicas} replica(s) | ${config.resources.memory}
    %{endfor~}
    
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    📁 Generated Files
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    Reports:
    - environment-config-${var.environment}.json
    - cost-estimation-${var.environment}.txt
    - validation-report-${var.environment}.txt
    - dependency-map-${var.environment}.txt
    
    Service Configs:
    %{for service_name in keys(local.service_configs)~}
    - services/${service_name}-config.yaml
    %{endfor~}
    
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    🎓 Learning Outcomes
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    
    ✅ Advanced Terraform locals and variables
    ✅ Dynamic configuration generation with for expressions
    ✅ Complex validation logic
    ✅ Template rendering and file generation
    ✅ Dependency mapping and service discovery
    ✅ Multi-environment management
    ✅ Cost estimation and resource planning
    
    ╔════════════════════════════════════════════════════════════════╗
    ║                    🎉 ALL EXERCISES COMPLETED! 🎉              ║
    ╚════════════════════════════════════════════════════════════════╝
  EOF
}
