version: '3.8'
services:
  vote:
    build: ./vote  # Cambiado temporalmente de image a build
    ports:
      - "8082:5000"  # Agregado puertos
    environment:
      - FLASK_ENV=production
      - DB_NAME=voting
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - voting-net

  result:
    build: ./result  # Cambiado temporalmente de image a build
    ports:
      - "3002:3000"  # Agregado puertos
    environment:
      - NODE_ENV=production
      - DB_NAME=voting
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - voting-net

  worker:
    build: ./worker  # Cambiado temporalmente de image a build
    environment:
      - NODE_ENV=production
      - DB_NAME=voting
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=database
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - voting-net

  redis:
    image: redis:alpine
    networks:
      - voting-net  # Corregido para consistencia
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=voting
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - voting-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d voting"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  voting-net:
    driver: bridge

volumes:
  pgdata: