Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.10"

  # Redirección de Puertos (esto no cambia)
  config.vm.network "forwarded_port", guest: 5000, host: 8080
  config.vm.network "forwarded_port", guest: 3000, host: 3000

    config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.config_file = "ansible.cfg"
  end
end
